import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './globals.scss'
import { ConfirmProvider } from '@/components/ConfirmDialog/ConfirmContext'
import { AuthProvider } from '@/context/AuthContext'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Focus Director',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ConfirmProvider>

            <div className="mainPage">
              {children}
            </div>

          <Toaster
            position="top-center"
            offset={20}
            richColors
            closeButton
            toastOptions={{
              duration: 3000,
              style: {
                background: "#000",
                border: "1px solid #444",
                borderRadius: "10px",
              },
            }}
          />

          </ConfirmProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
