import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './globals.scss'
import { ConfirmProvider } from '@/components/ConfirmDialog/ConfirmContext'
import { AuthProvider } from '@/context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Focus Director',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ConfirmProvider>
            {children}
          </ConfirmProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
