import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../globals.css'
import '../../globals.scss'
import { ConfirmProvider } from '@/components/ConfirmDialog/ConfirmContext'
import DashboardNav from './DashboardNav'
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { toast } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Focus Director',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const auth = cookies().get("auth_token");

  if (!auth) {
    redirect("/login");
    toast.warning("Login required.")
  }
  return (
        <ConfirmProvider>
          <div className="mainPage">
            <DashboardNav />
            <main>{children}</main>
          </div>
        </ConfirmProvider>
  )
}